spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jorian_framework?useUnicode=yes&characterEncoding=UTF8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
files:
  path: "/usr/local/src/files"
  url: "jorianye.cn:8084"











